### ISSUE TITLE
First release roadmap and misc. todo

### ISSUE THREAD

**Issue by Phil-V** [Phil-V/rgeocoder#1]
- [x] Get Travis CI builds to work for mac and linux
- [x] Write some missing module documentation
- [x] Clean up some of the README and pypi presentation
- [x] Use Appveyor CI for windows builds
- [x] Build and distribute a source package
